# Generated by Django 5.2.14 on 2026-05-20 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('deposit', 'Consignación')], max_length=10, verbose_name='Método de pago')),
                ('supplier', models.CharField(max_length=200, verbose_name='Proveedor')),
                ('invoice_number', models.CharField(max_length=100, verbose_name='N° Factura')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('bank', models.CharField(blank=True, choices=[('agrario', 'Banco Agrario'), ('bancolombia', 'Bancolombia'), ('bogota', 'Banco de Bogotá')], max_length=30, null=True, verbose_name='Banco')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='businesses.business', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Egreso',
                'verbose_name_plural': 'Egresos',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('deposit', 'Consignación')], max_length=10, verbose_name='Método de pago')),
                ('bank', models.CharField(blank=True, choices=[('agrario', 'Banco Agrario'), ('bancolombia', 'Bancolombia'), ('bogota', 'Banco de Bogotá')], max_length=30, null=True, verbose_name='Banco')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='businesses.business', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
