# Generated by Django 5.2.14 on 2026-06-02 02:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del banco')),
                ('slug', models.SlugField(help_text='Identificador único, ej: bancolombia, agrario, bogota', unique=True)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Saldo inicial')),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Saldo actual')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('receives_transfers', models.BooleanField(default=False, help_text='Solo esta cuenta aumenta cuando hay ingresos por consignación', verbose_name='Recibe transferencias de ingresos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cuenta bancaria',
                'verbose_name_plural': 'Cuentas bancarias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CashClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(unique=True, verbose_name='Fecha')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Saldo inicial')),
                ('physical_cash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Efectivo contado')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Cerrado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Cuadre de caja',
                'verbose_name_plural': 'Cuadres de caja',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del turno')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('deposit', 'Consignación')], max_length=10, verbose_name='Método de pago')),
                ('supplier', models.CharField(blank=True, max_length=200, null=True, verbose_name='Proveedor')),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Factura')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('expense_type', models.CharField(choices=[('purchase', 'Compra'), ('general_expense', 'Gasto externo / retiro efectivo'), ('staff_payment', 'Pago a personal'), ('other', 'Otros')], default='general_expense', max_length=30, verbose_name='Tipo de egreso')),
                ('employee_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Persona pagada')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='cash_closing.bankaccount', verbose_name='Banco')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='businesses.business', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Egreso',
                'verbose_name_plural': 'Egresos',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('deposit', 'Consignación')], max_length=10, verbose_name='Método de pago')),
                ('person_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Persona que ingresó')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='cash_closing.bankaccount', verbose_name='Banco')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='businesses.business', verbose_name='Negocio')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cash_closing.shift', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashDenomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(100000, '$100.000'), (50000, '$50.000'), (20000, '$20.000'), (10000, '$10.000'), (5000, '$5.000'), (2000, '$2.000'), (1000, '$1.000'), (500, '$500'), (200, '$200'), (100, '$100'), (50, '$50')], verbose_name='Denominación')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('closing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denominations', to='cash_closing.cashclosing')),
            ],
            options={
                'verbose_name': 'Denominación',
                'verbose_name_plural': 'Denominaciones',
                'ordering': ['-value'],
                'unique_together': {('closing', 'value')},
            },
        ),
    ]
