# Generated by Django 5.2.14 on 2026-06-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_closing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('purchase', 'Compra a proveedor'), ('general_expense', 'Gasto externo / retiro efectivo'), ('staff_payment', 'Gastos de nómina'), ('other', 'Otros')], default='general_expense', max_length=30, verbose_name='Tipo de egreso'),
        ),
    ]
