# Generated by Django 5.2.14 on 2026-05-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cash_closing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="income",
            name="shift",
            field=models.IntegerField(
                choices=[(1, "Turno 1"), (2, "Turno 2")],
                default=1,
                verbose_name="Turno",
            ),
            preserve_default=False,
        ),
    ]
