# Generated by Django 5.2.14 on 2026-05-17 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        ('cash_closing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=200, verbose_name='Proveedor')),
                ('invoice_number', models.CharField(max_length=100, verbose_name='N° factura')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_expenses', to='businesses.business', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Egreso efectivo',
                'verbose_name_plural': 'Egresos efectivo',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
