# Generated by Django 5.2.14 on 2026-05-22 02:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_closing', '0002_income_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(unique=True, verbose_name='Fecha')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Saldo inicial')),
                ('physical_cash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Efectivo contado')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Cerrado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Cuadre de caja',
                'verbose_name_plural': 'Cuadres de caja',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CashDenomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(100000, '$100.000'), (50000, '$50.000'), (20000, '$20.000'), (10000, '$10.000'), (5000, '$5.000'), (2000, '$2.000'), (1000, '$1.000'), (500, '$500'), (200, '$200'), (100, '$100'), (50, '$50')], verbose_name='Denominación')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('closing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denominations', to='cash_closing.cashclosing')),
            ],
            options={
                'verbose_name': 'Denominación',
                'verbose_name_plural': 'Denominaciones',
                'ordering': ['-value'],
                'unique_together': {('closing', 'value')},
            },
        ),
    ]
