# Generated by Django 5.2.14 on 2026-06-04 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cash_closing", "0002_alter_expense_expense_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Proveedor"
                    ),
                ),
            ],
            options={
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="expense",
            name="supplier",
        ),
        migrations.AddField(
            model_name="expense",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expenses",
                to="cash_closing.supplier",
                verbose_name="Proveedor",
            ),
        ),
    ]
