# Generated by Django 5.2.14 on 2026-06-04 02:33

import django.db.models.deletion
from django.db import migrations, models

def migrate_suppliers_forward(apps, schema_editor):
    Expense = apps.get_model("cash_closing", "Expense")
    Supplier = apps.get_model("cash_closing", "Supplier")

    names = (
        Expense.objects
        .exclude(supplier__isnull=True)
        .exclude(supplier="")
        .values_list("supplier", flat=True)
        .distinct()
    )
    for name in names:
        supplier_obj, _ = Supplier.objects.get_or_create(name=name.strip())
        Expense.objects.filter(supplier=name).update(supplier_fk=supplier_obj)


def migrate_suppliers_backward(apps, schema_editor):
    Expense = apps.get_model("cash_closing", "Expense")
    for expense in Expense.objects.exclude(supplier_fk__isnull=True):
        expense.supplier_old = expense.supplier_fk.name
        expense.save(update_fields=["supplier_old"])


class Migration(migrations.Migration):

    dependencies = [
        ('cash_closing', '0002_alter_expense_expense_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['name'],
            },
        ),

        migrations.AddField(
            model_name='expense',
            name='supplier_fk',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='expenses',
                to='cash_closing.supplier',
                verbose_name='Proveedor',
            ),
        ),

        migrations.RunPython(migrate_suppliers_forward, migrate_suppliers_backward),

        migrations.RemoveField(model_name='expense', name='supplier'),

        migrations.RenameField(
            model_name='expense',
            old_name='supplier_fk',
            new_name='supplier',
        ),
    ]