# Generated by Django 5.2.14 on 2026-05-26 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_closing', '0003_cashclosing_cashdenomination'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='expense',
            name='employee_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Persona pagada'),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('purchase', 'Compra'), ('general_expense', 'Gasto externo / retiro efectivo'), ('staff_payment', 'Pago a personal'), ('other', 'Otros')], default='general_expense', max_length=30, verbose_name='Tipo de egreso'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Factura'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='supplier',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Proveedor'),
        ),
    ]
