# Generated by Django 5.2.14 on 2026-05-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_closing', '0004_expense_description_expense_employee_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='person_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Persona que ingresó'),
        ),
    ]
