# Generated by Django 5.2.14 on 2026-05-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_closing', '0008_remove_bank_old'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['name'], 'verbose_name': 'Cuenta Bancaria', 'verbose_name_plural': 'Cuentas Bancarias'},
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='current_balance',
            field=models.IntegerField(default=0, verbose_name='Saldo Actual'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='initial_balance',
            field=models.IntegerField(default=0, verbose_name='Saldo inicial'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='receives_transfers',
            field=models.BooleanField(default=False, help_text='Solo esta cuenta aumenta cuando hay ingresos por consignación', verbose_name='Recibe Transferencias de ingresos'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='slug',
            field=models.SlugField(help_text='Identificador único, ej: Bancolombia, Agrario, Bogotá', unique=True),
        ),
    ]
