# Generated by Django 5.2.14 on 2026-05-27 03:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_closing', '0009_alter_bankaccount_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['name'], 'verbose_name': 'Cuenta bancaria', 'verbose_name_plural': 'Cuentas bancarias'},
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Saldo actual'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Saldo inicial'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='receives_transfers',
            field=models.BooleanField(default=False, help_text='Solo esta cuenta aumenta cuando hay ingresos por consignación', verbose_name='Recibe transferencias de ingresos'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='slug',
            field=models.SlugField(help_text='Identificador único, ej: bancolombia, agrario, bogota', unique=True),
        ),
    ]
