# Generated by Django 5.2.14 on 2026-06-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, verbose_name='Número de factura')),
                ('purchase_date', models.DateField(verbose_name='Fecha')),
                ('product', models.CharField(max_length=255, verbose_name='Productos')),
                ('supplier', models.CharField(max_length=255, verbose_name='Proveedor')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-purchase_date'],
            },
        ),
    ]
