# Generated by Django 5.2.14 on 2026-05-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.CharField(max_length=255, verbose_name='Productos'),
        ),
    ]
